#!/usr/bin/env bash
#
# Setup ERPNext
#
# Copyright (C) 2021  Gilbertsoft
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Force some bash options see https://gist.github.com/mohanpedala/1e2ff5661761d3abd0385e8223e16425
set -euo pipefail
IFS=$'\n\t'

# Activate debugging if $DEBUG is set to 1
DEBUG=${DEBUG:-}
[ -z "$DEBUG" ] & [ "${DEBUG}" == 1 ] && set -o xtrace


# Functions
setup_config () {
    # Create .env.local from dist
    if [ ! -f ".env.local" ]; then
        echo "Generating .env.local..."
        envsubst '${USER}
            ${WEBSITE_SERVER_NAME}' \
            < .env.dist > .env.local
    fi

    # Create .env.credentials.local
    if [ ! -f ".env.credentials.local" ]; then
        echo "Generating .env.credentials.local..."
        echo "MYSQL_ROOT_PASSWORD=`pwgen -s 32 1`" > .env.credentials.local
    fi
}

setup_docker () {
    # Pull new images
    docker-compose pull

    # Restart containers
    docker-compose up -d
}


# Main
setup_config
setup_docker

echo
echo "ERPNext is installed and up to date now!"
